service: eks-scaler
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 128
  timeout: 10
  architecture: arm64
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - autoscaling:DescribeAutoScalingGroups
            - autoscaling:UpdateAutoScalingGroup
          Resource: "*"

functions:
  scaler:
    name: eks-scaler
    stage: dev
    handler: src/handler.handler
    description: Escala nodes EKS baseado na tag stop=yes e ação (scaleUp/scaleDown)
    events:
      - schedule:
          rate: cron(0 22 * * ? *) # 19h BRT (scaleDown)
          input:
            action: scaleDown
      - schedule:
          rate: cron(0 10 * * ? *) # 7h BRT (scaleUp)
          input:
            action: scaleUp

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    target: node18
    platform: node
    format: cjs
