service: eks-rds-scaler
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 128
  timeout: 10
  architecture: arm64
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

functions:
  eksScaler:
    name: eks-scaler
    handler: src/eksScaler.handler
    description: Escala nodes EKS baseado na tag stop=yes e ação (scaleUp/scaleDown)
    role: EksScalerLambdaRole
    events:
      - schedule:
          rate: cron(0 22 * * ? *) # 19h BRT (scaleDown)
          input:
            action: scaleDown
      - schedule:
          rate: cron(0 10 ? * 2-6 *) # 7h BRT MON-FRI (scaleUp)
          input:
            action: scaleUp
  rdsScaler:
    name: rds-scaler
    handler: src/rdsScaler.handler
    description: Gerencia start/stop instâncias RDS
    role: RdsScalerLambdaRole
    events:
      - schedule:
          rate: cron(0 22 * * ? *) # 19h BRT
          input:
            action: stop
      - schedule:
          rate: cron(0 10 ? * 2-6 *) # 7h BRT MON-FRI
          input:
            action: start

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    target: node18
    platform: node
    format: cjs

resources:
  Resources:
    EksScalerLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: eks-scaler-lambda-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: eksScalerPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - autoscaling:DescribeAutoScalingGroups
                    - autoscaling:UpdateAutoScalingGroup
                  Resource: "*"
    RdsScalerLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: rds-scaler-lambda-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: rdsScalerPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - rds:DescribeDBInstances
                    - rds:ListTagsForResource
                    - rds:StopDBInstance
                    - rds:StartDBInstance
                  Resource: "*"