name: Deploy Lambda

on:
  workflow_dispatch:
    inputs:
      envs:
        type: choice
        description: 'Select the environment to deploy'
        required: true
        default: 'dev'
        options:
          - dev
          - stg
          - prod

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.envs || 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy with Serverless
        env:
          ENV: ${{ github.event.inputs.envs || 'dev' }}
        run: sls deploy --stage ${ENV}
